/// ═══════════════════════════════════════════════════════════════════════════
/// EXPANDED BUYERS DATABASE - 100+ Real Studio/Streamer/Indie Profiles
/// Last Updated: July 2025 (Data from 2024-2025 acquisitions & trade press)
/// ═══════════════════════════════════════════════════════════════════════════
/// 
/// Sources:
/// - Variety/Hollywood Reporter deal announcements
/// - Deadline/The Wrap acquisition reports
/// - Company investor presentations & earnings calls
/// - Festival acquisition trackers (Sundance, TIFF, Cannes)

library;

import 'industry_data.dart';

/// ═══════════════════════════════════════════════════════════════════════════
/// EXPANDED BUYER DATABASE - 100+ Industry Buyers
/// ═══════════════════════════════════════════════════════════════════════════

const List<BuyerProfile> expandedBuyerDatabase = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MAJOR STREAMERS (Global)
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'Netflix Film',
    type: 'Streamer',
    preferredGenres: ['Thriller', 'Action', 'Romance', 'Drama', 'Sci-Fi', 'Horror', 'Comedy'],
    contentStrategy: 'High-volume diverse content with global appeal. Focus on high-concept originals with star attachments. 2024: 302M subscribers, \$17B content spend.',
    recentAcquisitions: ['Rebel Ridge', 'Hit Man', 'The Electric State', 'Leave the World Behind', 'Glass Onion', 'Extraction 2', 'Heart of Stone'],
    budgetRange: '\$20M - \$200M',
    submissionTip: 'Netflix values diverse voices and fresh takes. Package with recognizable talent for best results. Four-quadrant appeal preferred.',
    baseMatchScore: 88,
    acceptsUnsolicited: false,
    territoryFocus: 'Global (190+ countries)',
  ),
  BuyerProfile(
    name: 'Netflix Series',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Thriller', 'Sci-Fi', 'Fantasy', 'Horror', 'Comedy'],
    contentStrategy: 'Limited series and ongoing dramas. Strong IP development. Wednesday, Squid Game models.',
    recentAcquisitions: ['3 Body Problem', 'The Gentlemen', 'Fool Me Once', 'Ripley', 'Baby Reindeer'],
    budgetRange: '\$8M - \$25M per episode',
    submissionTip: 'Clear season arc essential. Limited series with defined endpoint preferred over open-ended.',
    baseMatchScore: 87,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Amazon MGM Studios - Film',
    type: 'Streamer',
    preferredGenres: ['Action', 'Thriller', 'Sci-Fi', 'Drama', 'Comedy', 'Romance'],
    contentStrategy: 'Franchise-building focus with theatrical-to-Prime pipeline. MGM library IP valued. 200M Prime subscribers.',
    recentAcquisitions: ['Road House', 'Saltburn', 'Air', 'The Idea of You', 'Creed III', 'Challengers'],
    budgetRange: '\$30M - \$250M',
    submissionTip: 'Emphasize franchise potential and theatrical viability. MGM legacy IP synergies welcome. Star packages essential.',
    baseMatchScore: 86,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Amazon MGM Studios - Series',
    type: 'Streamer',
    preferredGenres: ['Fantasy', 'Sci-Fi', 'Drama', 'Thriller', 'Action'],
    contentStrategy: 'Prestige series with event potential. Rings of Power model. Jack Ryan franchise.',
    recentAcquisitions: ['Fallout', 'The Boys', 'Citadel', 'Mr. & Mrs. Smith', 'The Lord of the Rings: Rings of Power'],
    budgetRange: '\$12M - \$50M+ per episode',
    submissionTip: 'World-building and franchise potential crucial. Multi-season vision required.',
    baseMatchScore: 85,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Apple TV+',
    type: 'Streamer',
    preferredGenres: ['Sci-Fi', 'Drama', 'Thriller', 'Documentary', 'Comedy'],
    contentStrategy: 'Prestige-first approach. Quality over quantity with A-list talent attachments. Awards-focused slate.',
    recentAcquisitions: ['Killers of the Flower Moon', 'Napoleon', 'Wolfs', 'Fly Me to the Moon', 'Argylle'],
    budgetRange: '\$50M - \$200M+',
    submissionTip: 'Apple prioritizes awards-caliber material. Director and star packages essential. Brand-safe content.',
    baseMatchScore: 90,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Apple TV+ Series',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Thriller', 'Sci-Fi', 'Comedy'],
    contentStrategy: 'Premium flagship series. Severance, The Morning Show, Ted Lasso caliber.',
    recentAcquisitions: ['Severance', 'Slow Horses', 'Shrinking', 'The Morning Show', 'Silo'],
    budgetRange: '\$10M - \$20M per episode',
    submissionTip: 'A-list showrunner or talent attachment required. High production values expected.',
    baseMatchScore: 89,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'HBO/Max',
    type: 'Streamer',
    preferredGenres: ['Fantasy', 'Drama', 'Thriller', 'Horror', 'Comedy', 'Documentary'],
    contentStrategy: 'Premium series and limited series focus. Strong IP development. Quality brand positioning.',
    recentAcquisitions: ['The Last of Us', 'House of the Dragon', 'True Detective: Night Country', 'The Sympathizer', 'Hacks'],
    budgetRange: '\$10M - \$20M per episode (series)',
    submissionTip: 'HBO values bold, distinctive voices. Limited series with clear endpoint preferred. Prestige pedigree.',
    baseMatchScore: 89,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Max Original Films',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Comedy', 'Thriller', 'Horror', 'Romance'],
    contentStrategy: 'Direct-to-streaming original films. Quality focus with theatrical crossover potential.',
    recentAcquisitions: ['Furiosa', 'Godzilla x Kong', 'Dune: Part Two', 'Beetlejuice Beetlejuice'],
    budgetRange: '\$15M - \$100M',
    submissionTip: 'Warner Bros theatrical rejects sometimes land here. Quality mid-budget focus.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Disney+',
    type: 'Streamer',
    preferredGenres: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi', 'Animation', 'Family'],
    contentStrategy: 'Marvel, Star Wars, Pixar, Disney core. 126M+ subscribers. Family-friendly focus.',
    recentAcquisitions: ['Percy Jackson', 'The Acolyte', 'Echo', 'Agatha All Along'],
    budgetRange: '\$15M - \$25M per episode',
    submissionTip: 'Content must fit Disney brand values. Franchise potential and family appeal essential.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Hulu Originals',
    type: 'Streamer',
    preferredGenres: ['Comedy', 'Drama', 'Thriller', 'Horror', 'Romance', 'True Crime'],
    contentStrategy: 'Young adult focus, limited series, diverse voices. Next-day broadcast partner.',
    recentAcquisitions: ['No One Will Save You', 'Prey', 'The Bear', 'Only Murders in the Building', 'Shōgun'],
    budgetRange: '\$10M - \$50M',
    submissionTip: 'Hulu excels at contained thrillers and comedy. Younger demo preferred. 18-34 target.',
    baseMatchScore: 81,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Peacock',
    type: 'Streamer',
    preferredGenres: ['Mystery', 'Drama', 'Thriller', 'Comedy', 'Documentary', 'True Crime'],
    contentStrategy: 'True crime, procedurals, NBC legacy IP. Sports integration. 34M+ subscribers.',
    recentAcquisitions: ['Poker Face', 'Based on a True Story', 'Twisted Metal', 'Apples Never Fall'],
    budgetRange: '\$5M - \$40M',
    submissionTip: 'Peacock values procedural formats and true crime adaptations. NBC synergy welcome.',
    baseMatchScore: 79,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Paramount+',
    type: 'Streamer',
    preferredGenres: ['Action', 'Thriller', 'Sci-Fi', 'Drama', 'Comedy', 'Horror'],
    contentStrategy: 'Star Trek, Yellowstone universe, Paramount Pictures overflow. 71M+ subscribers.',
    recentAcquisitions: ['Yellowstone', 'Tulsa King', 'Special Ops: Lioness', '1923', 'Star Trek: Strange New Worlds'],
    budgetRange: '\$8M - \$15M per episode',
    submissionTip: 'Franchise extensions valued. Taylor Sheridan-style programming in demand.',
    baseMatchScore: 80,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // MAJOR STUDIOS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'Universal Pictures',
    type: 'Major Studio',
    preferredGenres: ['Horror', 'Comedy', 'Action', 'Animation', 'Thriller', 'Drama'],
    contentStrategy: 'Franchise focus with Blumhouse partnership. Strong theatrical commitment. Illumination animation.',
    recentAcquisitions: ['M3GAN', 'Oppenheimer', 'The Fall Guy', 'Abigail', 'Wicked', 'Twisters'],
    budgetRange: '\$5M - \$200M',
    submissionTip: 'Universal excels at mid-budget genre films. Horror and comedy sweet spots. Blumhouse model.',
    baseMatchScore: 85,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Universal Focus Features',
    type: 'Mini-Major',
    preferredGenres: ['Drama', 'Romance', 'Thriller', 'Comedy', 'Documentary'],
    contentStrategy: 'Quality-driven specialty films, international co-productions. Awards focus.',
    recentAcquisitions: ['The Bikeriders', 'Conclave', 'Drive-Away Dolls', 'Land of Bad'],
    budgetRange: '\$8M - \$35M',
    submissionTip: 'Focus values character-driven stories with international appeal. Director vision critical.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'US/International',
  ),
  BuyerProfile(
    name: 'Warner Bros. Pictures',
    type: 'Major Studio',
    preferredGenres: ['Action', 'Sci-Fi', 'Fantasy', 'Drama', 'Horror', 'Comedy'],
    contentStrategy: 'Theatrical tentpoles and DC Universe rebuild. Prestige dramas via New Line.',
    recentAcquisitions: ['Dune: Part Two', 'Beetlejuice Beetlejuice', 'Joker: Folie à Deux', 'Godzilla x Kong'],
    budgetRange: '\$50M - \$300M+',
    submissionTip: 'Focus on franchise potential and visual spectacle. IP-driven projects favored.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'New Line Cinema',
    type: 'Major Studio',
    preferredGenres: ['Horror', 'Comedy', 'Drama', 'Thriller'],
    contentStrategy: 'Conjuring Universe, mid-budget genre. Part of Warner Bros Discovery.',
    recentAcquisitions: ['It Ends with Us', 'Longlegs', 'The Nun II', 'Evil Dead Rise'],
    budgetRange: '\$20M - \$80M',
    submissionTip: 'Horror franchise potential valued. Rom-com revival interest.',
    baseMatchScore: 83,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Paramount Pictures',
    type: 'Major Studio',
    preferredGenres: ['Action', 'Horror', 'Thriller', 'Sci-Fi', 'Comedy', 'Animation'],
    contentStrategy: 'Legacy franchises (MI, Transformers, Star Trek) plus horror hits. Skydance merger pending.',
    recentAcquisitions: ['A Quiet Place: Day One', 'IF', 'Mission: Impossible - Dead Reckoning', 'Teenage Mutant Ninja Turtles'],
    budgetRange: '\$20M - \$200M',
    submissionTip: 'Paramount values high-concept premises with franchise potential.',
    baseMatchScore: 83,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Sony/TriStar Pictures',
    type: 'Major Studio',
    preferredGenres: ['Action', 'Romance', 'Animation', 'Comedy', 'Horror', 'Thriller'],
    contentStrategy: 'Spider-Verse universe, diverse slate, Sony Classics for prestige.',
    recentAcquisitions: ['Anyone But You', 'Bad Boys: Ride or Die', 'Madame Web', 'Ghostbusters: Frozen Empire'],
    budgetRange: '\$30M - \$200M',
    submissionTip: 'Sony responds well to star-driven packages and high-concept IP.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Sony Pictures Classics',
    type: 'Mini-Major',
    preferredGenres: ['Drama', 'Documentary', 'Comedy', 'Foreign Language'],
    contentStrategy: 'Festival acquisitions, international cinema, awards positioning.',
    recentAcquisitions: ['All of Us Strangers', 'The Holdovers', 'Past Lives', 'Anatomy of a Fall'],
    budgetRange: '\$3M - \$25M',
    submissionTip: 'Festival premiere essential. International co-productions welcome.',
    baseMatchScore: 86,
    acceptsUnsolicited: false,
    territoryFocus: 'US/International',
  ),
  BuyerProfile(
    name: 'Disney/20th Century Studios',
    type: 'Major Studio',
    preferredGenres: ['Fantasy', 'Animation', 'Action', 'Sci-Fi', 'Adventure', 'Horror'],
    contentStrategy: 'Marvel, Star Wars, Pixar, core Disney. 20th Century for mature content.',
    recentAcquisitions: ['Kingdom of the Planet of the Apes', 'Alien: Romulus', 'Inside Out 2', 'Deadpool & Wolverine'],
    budgetRange: '\$100M - \$400M+',
    submissionTip: 'Disney prioritizes family-friendly fare. 20th Century open to R-rated.',
    baseMatchScore: 87,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Searchlight Pictures',
    type: 'Mini-Major',
    preferredGenres: ['Drama', 'Comedy', 'Mystery', 'Horror', 'Romance'],
    contentStrategy: 'Awards-focused, prestige fare with commercial crossover potential.',
    recentAcquisitions: ['Poor Things', 'All of Us Strangers', 'A Real Pain', 'Kinds of Kindness'],
    budgetRange: '\$10M - \$40M',
    submissionTip: 'Searchlight excels at Oscar-caliber material. Director attachments crucial.',
    baseMatchScore: 88,
    acceptsUnsolicited: false,
    territoryFocus: 'US/UK/International',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // SPECIALTY/INDIE DISTRIBUTORS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'A24',
    type: 'Indie',
    preferredGenres: ['Horror', 'Drama', 'Thriller', 'Comedy', 'Sci-Fi'],
    contentStrategy: 'Auteur-driven, elevated genre, cultural impact over box office. Brand identity strongest in industry.',
    recentAcquisitions: ['Civil War', 'Love Lies Bleeding', 'MaXXXine', 'Sing Sing', 'We Live in Time'],
    budgetRange: '\$5M - \$50M',
    submissionTip: 'A24 values unique voices and singular vision. Director-driven packages preferred. Festival pedigree helps.',
    baseMatchScore: 91,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Select International',
  ),
  BuyerProfile(
    name: 'Neon',
    type: 'Indie',
    preferredGenres: ['Horror', 'Drama', 'Thriller', 'Documentary', 'Sci-Fi', 'Comedy'],
    contentStrategy: 'Bold, provocative content. Festival acquisitions and originals. Parasite, Longlegs model.',
    recentAcquisitions: ['Longlegs', 'Anora', 'Immaculate', 'The Substance', 'Cuckoo'],
    budgetRange: '\$3M - \$25M',
    submissionTip: 'Neon seeks conversation-starting films. Festival pedigree essential. Provocative preferred.',
    baseMatchScore: 87,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Select International',
  ),
  BuyerProfile(
    name: 'Lionsgate',
    type: 'Mini-Major',
    preferredGenres: ['Action', 'Thriller', 'Horror', 'Comedy', 'Drama'],
    contentStrategy: 'Franchise-focused (John Wick, Hunger Games, SAW). Genre expertise.',
    recentAcquisitions: ['The Killer', 'John Wick: Chapter 4', 'Borderlands', 'The Strangers: Chapter 1'],
    budgetRange: '\$15M - \$100M',
    submissionTip: 'Lionsgate values franchise potential and star-driven action.',
    baseMatchScore: 83,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Lionsgate Summit',
    type: 'Mini-Major',
    preferredGenres: ['Drama', 'Romance', 'Thriller', 'Comedy'],
    contentStrategy: 'Mid-budget prestige and genre films. Awards season positioning.',
    recentAcquisitions: ['La La Land', 'Moonlight', 'Hacksaw Ridge'],
    budgetRange: '\$10M - \$40M',
    submissionTip: 'Awards-caliber material with commercial hooks.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'US/International',
  ),
  BuyerProfile(
    name: 'IFC Films',
    type: 'Indie',
    preferredGenres: ['Drama', 'Horror', 'Documentary', 'Comedy', 'Foreign Language'],
    contentStrategy: 'Day-and-date theatrical/VOD strategy. Festival acquisitions.',
    recentAcquisitions: ['The Zone of Interest', 'Problemista', 'Sometimes I Think About Dying'],
    budgetRange: '\$1M - \$15M',
    submissionTip: 'Festival premiere preferred. Adventurous programming.',
    baseMatchScore: 78,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Magnolia Pictures',
    type: 'Indie',
    preferredGenres: ['Documentary', 'Drama', 'Horror', 'Foreign Language', 'Thriller'],
    contentStrategy: 'Documentary leader, international cinema, genre acquisitions.',
    recentAcquisitions: ['BlackBerry', 'How to Blow Up a Pipeline', 'TÁR'],
    budgetRange: '\$500K - \$10M',
    submissionTip: 'Festival premiere essential. Documentary expertise.',
    baseMatchScore: 76,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Bleecker Street',
    type: 'Indie',
    preferredGenres: ['Drama', 'Thriller', 'Documentary', 'Comedy'],
    contentStrategy: 'Prestige theatrical releases. Oscar-positioning expertise.',
    recentAcquisitions: ['The Old Man and the Gun', 'Late Night', 'Brian and Charles'],
    budgetRange: '\$5M - \$20M',
    submissionTip: 'Awards potential important. Star attachments help.',
    baseMatchScore: 80,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Roadside Attractions',
    type: 'Indie',
    preferredGenres: ['Drama', 'Documentary', 'Comedy', 'Romance'],
    contentStrategy: 'Theatrical specialty releases. Faith-based content success.',
    recentAcquisitions: ['Manchester by the Sea', 'American Honey', 'Whitney'],
    budgetRange: '\$5M - \$25M',
    submissionTip: 'Strong word-of-mouth potential important.',
    baseMatchScore: 79,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'MUBI',
    type: 'Indie',
    preferredGenres: ['Drama', 'Foreign Language', 'Documentary', 'Thriller', 'Horror'],
    contentStrategy: 'Curated streaming with theatrical releases. Art house focus. 15M+ subscribers.',
    recentAcquisitions: ['Passages', 'Aftersun', 'Saint Omer', 'The Substance'],
    budgetRange: '\$500K - \$15M',
    submissionTip: 'Festival pedigree essential. Art house sensibility required.',
    baseMatchScore: 81,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Oscilloscope Laboratories',
    type: 'Indie',
    preferredGenres: ['Documentary', 'Drama', 'Comedy', 'Experimental'],
    contentStrategy: 'Adventurous programming, documentary focus. Adam Yauch legacy.',
    recentAcquisitions: ['We Are the Best!', 'The Ambassador', 'Detropia'],
    budgetRange: '\$500K - \$5M',
    submissionTip: 'Unique voice and vision essential. Documentary expertise.',
    baseMatchScore: 74,
    acceptsUnsolicited: true,
    territoryFocus: 'US',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // PRODUCTION COMPANIES / FIRST-LOOK DEALS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'Blumhouse Productions',
    type: 'Production Company',
    preferredGenres: ['Horror', 'Thriller', 'Sci-Fi'],
    contentStrategy: 'Low-budget horror model (\$3-15M). High volume, high ROI focus. Universal deal.',
    recentAcquisitions: ['M3GAN', 'Five Nights at Freddy\'s', 'The Black Phone', 'Imaginary', 'Insidious: The Red Door'],
    budgetRange: '\$3M - \$15M',
    submissionTip: 'Blumhouse wants contained horror with fresh concepts. Low budget, high concept.',
    baseMatchScore: 94,
    acceptsUnsolicited: true,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Plan B Entertainment',
    type: 'Production Company',
    preferredGenres: ['Drama', 'Thriller', 'Documentary', 'Comedy'],
    contentStrategy: 'Brad Pitt\'s banner. Prestige focus, socially relevant material.',
    recentAcquisitions: ['12 Years a Slave', 'Moonlight', 'The Big Short', 'She Said', 'Women Talking'],
    budgetRange: '\$15M - \$80M',
    submissionTip: 'Socially relevant stories, underrepresented voices, awards potential.',
    baseMatchScore: 89,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'LuckyChap Entertainment',
    type: 'Production Company',
    preferredGenres: ['Comedy', 'Drama', 'Thriller', 'Romance'],
    contentStrategy: 'Margot Robbie\'s banner. Female-focused storytelling.',
    recentAcquisitions: ['Barbie', 'I, Tonya', 'Promising Young Woman', 'Birds of Prey', 'Saltburn'],
    budgetRange: '\$25M - \$150M',
    submissionTip: 'Female-led stories with edge, dark comedy, unconventional narratives.',
    baseMatchScore: 88,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Legendary Entertainment',
    type: 'Production Company',
    preferredGenres: ['Action', 'Sci-Fi', 'Fantasy', 'Horror'],
    contentStrategy: 'Monsterverse, Dune franchise. Tentpole focus with WB partnership.',
    recentAcquisitions: ['Dune: Part Two', 'Godzilla x Kong', 'Challengers', 'Enola Holmes'],
    budgetRange: '\$80M - \$200M+',
    submissionTip: 'Franchise potential essential. Visual spectacle focus.',
    baseMatchScore: 86,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Skydance Media',
    type: 'Production Company',
    preferredGenres: ['Action', 'Sci-Fi', 'Thriller', 'Animation'],
    contentStrategy: 'Mission: Impossible, Jack Reacher, Top Gun franchise partnerships.',
    recentAcquisitions: ['Top Gun: Maverick', 'Mission: Impossible - Dead Reckoning', 'The Adam Project'],
    budgetRange: '\$50M - \$200M',
    submissionTip: 'Star-driven action with franchise potential. Tom Cruise relationship.',
    baseMatchScore: 85,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Bad Robot',
    type: 'Production Company',
    preferredGenres: ['Sci-Fi', 'Thriller', 'Mystery', 'Action', 'Horror'],
    contentStrategy: 'J.J. Abrams\' company. Mystery box narratives, franchise IP.',
    recentAcquisitions: ['Cloverfield', 'Westworld', '10 Cloverfield Lane', 'Star Trek'],
    budgetRange: '\$60M - \$200M',
    submissionTip: 'Mystery box narratives, sci-fi spectacle, franchise IP.',
    baseMatchScore: 86,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Atomic Monster',
    type: 'Production Company',
    preferredGenres: ['Horror', 'Thriller', 'Action'],
    contentStrategy: 'James Wan\'s company. Conjuring Universe, Aquaman franchise.',
    recentAcquisitions: ['The Conjuring', 'Insidious', 'Aquaman', 'M3GAN', 'Malignant'],
    budgetRange: '\$20M - \$200M',
    submissionTip: 'Franchise-potential horror/action. Visual spectacle with scares.',
    baseMatchScore: 90,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'T-Street',
    type: 'Production Company',
    preferredGenres: ['Mystery', 'Thriller', 'Sci-Fi', 'Drama'],
    contentStrategy: 'Rian Johnson\'s company. Knives Out franchise, Poker Face.',
    recentAcquisitions: ['Knives Out', 'Glass Onion', 'Poker Face', 'Looper'],
    budgetRange: '\$40M - \$100M',
    submissionTip: 'Clever whodunits, genre-bending mysteries, limited series.',
    baseMatchScore: 91,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Hello Sunshine',
    type: 'Production Company',
    preferredGenres: ['Drama', 'Romance', 'Thriller', 'Documentary'],
    contentStrategy: 'Reese Witherspoon\'s company. Female-driven, book adaptations.',
    recentAcquisitions: ['Big Little Lies', 'The Morning Show', 'Where the Crawdads Sing', 'Daisy Jones'],
    budgetRange: '\$20M - \$60M',
    submissionTip: 'Female-driven stories, book adaptations, limited series.',
    baseMatchScore: 86,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Syncopy',
    type: 'Production Company',
    preferredGenres: ['Sci-Fi', 'Thriller', 'Drama', 'Action'],
    contentStrategy: 'Christopher Nolan\'s company. Prestige blockbusters.',
    recentAcquisitions: ['Oppenheimer', 'Tenet', 'Interstellar', 'Dunkirk'],
    budgetRange: '\$100M - \$250M',
    submissionTip: 'Cerebral, ambitious storytelling. Director-driven projects with vision.',
    baseMatchScore: 92,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: '87North',
    type: 'Production Company',
    preferredGenres: ['Action', 'Thriller', 'Comedy'],
    contentStrategy: 'David Leitch\'s company. Stunt-driven action films.',
    recentAcquisitions: ['John Wick', 'Bullet Train', 'Nobody', 'The Fall Guy', 'Atomic Blonde'],
    budgetRange: '\$50M - \$150M',
    submissionTip: 'Stunt-driven action with wit. Star vehicles with physical comedy.',
    baseMatchScore: 87,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Apatow Productions',
    type: 'Production Company',
    preferredGenres: ['Comedy', 'Drama', 'Romance'],
    contentStrategy: 'Judd Apatow\'s company. R-rated character-driven comedy.',
    recentAcquisitions: ['Superbad', 'Bridesmaids', 'Knocked Up', 'The King of Staten Island'],
    budgetRange: '\$30M - \$80M',
    submissionTip: 'Character-driven R-rated comedy. Emerging comedic voices.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Lord Miller',
    type: 'Production Company',
    preferredGenres: ['Comedy', 'Animation', 'Action', 'Sci-Fi'],
    contentStrategy: 'Phil Lord & Christopher Miller. Irreverent comedy, animation.',
    recentAcquisitions: ['Spider-Verse', 'The Lego Movie', '21 Jump Street', 'The Mitchells vs. the Machines'],
    budgetRange: '\$40M - \$120M',
    submissionTip: 'Irreverent comedy with heart. Animation and live-action hybrids.',
    baseMatchScore: 86,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Monkeypaw Productions',
    type: 'Production Company',
    preferredGenres: ['Horror', 'Thriller', 'Drama', 'Sci-Fi'],
    contentStrategy: 'Jordan Peele\'s company. Social horror, elevated genre.',
    recentAcquisitions: ['Get Out', 'Us', 'Nope', 'Candyman', 'BlacKkKlansman'],
    budgetRange: '\$5M - \$75M',
    submissionTip: 'Social commentary horror, unique perspective, elevated genre.',
    baseMatchScore: 91,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Double Dare You',
    type: 'Production Company',
    preferredGenres: ['Fantasy', 'Horror', 'Drama', 'Animation'],
    contentStrategy: 'Guillermo del Toro\'s company. Dark fairy tales, monster stories.',
    recentAcquisitions: ['The Shape of Water', 'Pan\'s Labyrinth', 'Nightmare Alley', 'Pinocchio'],
    budgetRange: '\$40M - \$120M',
    submissionTip: 'Dark fairy tales, visually distinctive fantasy, monster stories.',
    baseMatchScore: 89,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // INTERNATIONAL BUYERS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'StudioCanal',
    type: 'International',
    preferredGenres: ['Drama', 'Thriller', 'Action', 'Comedy', 'Horror'],
    contentStrategy: 'European major. Paddington, Working Title partnership. French/UK focus.',
    recentAcquisitions: ['Paddington', 'The Duke', 'Wild Bunch', 'Legend'],
    budgetRange: '\$20M - \$80M',
    submissionTip: 'European sensibility. Co-production friendly. UK/France focus.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'Europe/International',
  ),
  BuyerProfile(
    name: 'Entertainment One (eOne)',
    type: 'International',
    preferredGenres: ['Drama', 'Family', 'Horror', 'Thriller'],
    contentStrategy: 'Hasbro-owned. Peppa Pig, Transformers animation. Canadian/UK content.',
    recentAcquisitions: ['Transformers: Rise of the Beasts', 'The Twilight Zone', '1917'],
    budgetRange: '\$10M - \$100M',
    submissionTip: 'Family content and Hasbro IP synergies valued.',
    baseMatchScore: 79,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Pathé',
    type: 'International',
    preferredGenres: ['Drama', 'Documentary', 'Comedy', 'Foreign Language'],
    contentStrategy: 'French major. European art house and mainstream. Historic UK presence.',
    recentAcquisitions: ['Selma', 'The Imitation Game', 'Philomena'],
    budgetRange: '\$5M - \$50M',
    submissionTip: 'European co-production expertise. Awards-focused material.',
    baseMatchScore: 80,
    acceptsUnsolicited: false,
    territoryFocus: 'Europe/International',
  ),
  BuyerProfile(
    name: 'CJ Entertainment',
    type: 'International',
    preferredGenres: ['Action', 'Thriller', 'Drama', 'Horror', 'Comedy'],
    contentStrategy: 'Korean major. Parasite studio. K-content global expansion.',
    recentAcquisitions: ['Parasite', 'Snowpiercer', 'The Handmaiden', 'Train to Busan'],
    budgetRange: '\$10M - \$60M',
    submissionTip: 'Korean talent collaboration. Genre-bending material.',
    baseMatchScore: 85,
    acceptsUnsolicited: false,
    territoryFocus: 'Asia/Global',
  ),
  BuyerProfile(
    name: 'Toho International',
    type: 'International',
    preferredGenres: ['Horror', 'Sci-Fi', 'Animation', 'Drama'],
    contentStrategy: 'Japanese major. Godzilla rights holder. Anime distribution.',
    recentAcquisitions: ['Godzilla Minus One', 'Your Name', 'Shin Godzilla'],
    budgetRange: '\$10M - \$80M',
    submissionTip: 'Japanese co-production potential. Monster/kaiju expertise.',
    baseMatchScore: 78,
    acceptsUnsolicited: false,
    territoryFocus: 'Japan/Global',
  ),
  BuyerProfile(
    name: 'Gaumont',
    type: 'International',
    preferredGenres: ['Drama', 'Thriller', 'Comedy', 'Animation'],
    contentStrategy: 'French major. Oldest film company. Prestige and commercial slate.',
    recentAcquisitions: ['Intouchables', 'Lucy', 'Lupin (Netflix)'],
    budgetRange: '\$5M - \$60M',
    submissionTip: 'French language and international co-productions.',
    baseMatchScore: 79,
    acceptsUnsolicited: false,
    territoryFocus: 'France/Europe/Global',
  ),
  BuyerProfile(
    name: 'Constantin Film',
    type: 'International',
    preferredGenres: ['Action', 'Horror', 'Thriller', 'Fantasy'],
    contentStrategy: 'German major. Resident Evil franchise. German language content.',
    recentAcquisitions: ['Resident Evil', 'The Neverending Story', 'Dark (Netflix)'],
    budgetRange: '\$15M - \$80M',
    submissionTip: 'German co-production. Franchise horror expertise.',
    baseMatchScore: 77,
    acceptsUnsolicited: false,
    territoryFocus: 'Germany/Europe/Global',
  ),
  BuyerProfile(
    name: 'Film4',
    type: 'International',
    preferredGenres: ['Drama', 'Horror', 'Comedy', 'Thriller'],
    contentStrategy: 'Channel 4 film arm. British indie cinema. Award-winning slate.',
    recentAcquisitions: ['12 Years a Slave', 'Room', 'The Favourite', 'Saint Maud'],
    budgetRange: '\$3M - \$20M',
    submissionTip: 'British creative talent. Festival-worthy material. Low budget focus.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'UK/International',
  ),
  BuyerProfile(
    name: 'BBC Film',
    type: 'International',
    preferredGenres: ['Drama', 'Documentary', 'Comedy', 'Romance'],
    contentStrategy: 'BBC co-production arm. British stories with international appeal.',
    recentAcquisitions: ['Philomena', 'An Education', 'Pride', 'Sometimes I Think About Dying'],
    budgetRange: '\$2M - \$15M',
    submissionTip: 'British setting/talent. Theatrical and iPlayer combination.',
    baseMatchScore: 81,
    acceptsUnsolicited: false,
    territoryFocus: 'UK/International',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // FAITH-BASED / FAMILY CONTENT
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'Angel Studios',
    type: 'Indie',
    preferredGenres: ['Drama', 'Family', 'Faith', 'Documentary'],
    contentStrategy: 'Crowdfunded faith-based content. Sound of Freedom model.',
    recentAcquisitions: ['Sound of Freedom', 'The Chosen', 'His Only Son'],
    budgetRange: '\$5M - \$20M',
    submissionTip: 'Faith-based themes with broad appeal. Crowdfunding component.',
    baseMatchScore: 75,
    acceptsUnsolicited: true,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Pure Flix',
    type: 'Indie',
    preferredGenres: ['Drama', 'Family', 'Faith', 'Comedy'],
    contentStrategy: 'Faith-based streaming service. Christian content focus.',
    recentAcquisitions: ['God\'s Not Dead', 'Unplanned', 'Overcomer'],
    budgetRange: '\$3M - \$15M',
    submissionTip: 'Christian values essential. Family-friendly content only.',
    baseMatchScore: 72,
    acceptsUnsolicited: true,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Affirm Films',
    type: 'Mini-Major',
    preferredGenres: ['Drama', 'Family', 'Faith'],
    contentStrategy: 'Sony faith-based label. Mainstream crossover potential.',
    recentAcquisitions: ['Soul Surfer', 'Risen', 'The Star'],
    budgetRange: '\$10M - \$30M',
    submissionTip: 'Faith elements with mainstream appeal. Sony distribution backing.',
    baseMatchScore: 76,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // DOCUMENTARY SPECIALISTS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'National Geographic Documentary Films',
    type: 'Streamer',
    preferredGenres: ['Documentary', 'Nature', 'Science', 'Adventure'],
    contentStrategy: 'Premium documentary. Oscar-winning docs. Disney+ integration.',
    recentAcquisitions: ['Free Solo', 'The Rescue', 'Fire of Love', 'Becoming Cousteau'],
    budgetRange: '\$5M - \$25M',
    submissionTip: 'Visual spectacle important. Nature and adventure focus. Awards potential.',
    baseMatchScore: 83,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Participant Media',
    type: 'Production Company',
    preferredGenres: ['Documentary', 'Drama', 'Drama', 'Thriller'],
    contentStrategy: 'Social impact focus. Documentary and narrative. An Inconvenient Truth model.',
    recentAcquisitions: ['An Inconvenient Truth', 'CITIZENFOUR', 'Spotlight', 'Green Book'],
    budgetRange: '\$5M - \$40M',
    submissionTip: 'Social impact essential. Change-making content.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Altitude Film Distribution',
    type: 'Indie',
    preferredGenres: ['Documentary', 'Drama', 'Comedy', 'Horror'],
    contentStrategy: 'UK distributor. Music documentaries. Amy model.',
    recentAcquisitions: ['Amy', 'Moonlight', 'Lady Macbeth', '20 Days in Mariupol'],
    budgetRange: '\$2M - \$20M',
    submissionTip: 'UK release focus. Festival pedigree valued.',
    baseMatchScore: 77,
    acceptsUnsolicited: false,
    territoryFocus: 'UK/International',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // ANIMATION SPECIALISTS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'GKIDS',
    type: 'Indie',
    preferredGenres: ['Animation', 'Family', 'Fantasy', 'Drama'],
    contentStrategy: 'International animation distributor. Studio Ghibli partnership.',
    recentAcquisitions: ['The Boy and the Heron', 'Belle', 'Suzume', 'Wolfwalkers'],
    budgetRange: '\$5M - \$50M acquisition',
    submissionTip: 'Animation quality essential. International titles preferred.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Shout! Studios',
    type: 'Indie',
    preferredGenres: ['Animation', 'Documentary', 'Horror', 'Sci-Fi'],
    contentStrategy: 'Genre and animation distribution. Mystery Science Theater revival.',
    recentAcquisitions: ['Late Night with the Devil', 'Hundreds of Beavers', 'The Iron Giant'],
    budgetRange: '\$1M - \$15M',
    submissionTip: 'Cult appeal valued. Genre expertise.',
    baseMatchScore: 74,
    acceptsUnsolicited: true,
    territoryFocus: 'US',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // EMERGING STREAMERS & PLATFORMS
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'Tubi',
    type: 'Streamer',
    preferredGenres: ['Horror', 'Thriller', 'Action', 'Comedy', 'Drama'],
    contentStrategy: 'Free ad-supported streaming. Original content growing. Fox-owned.',
    recentAcquisitions: ['Terror on the Prairie', 'Swim', 'The Freak Brothers'],
    budgetRange: '\$1M - \$10M',
    submissionTip: 'Lower budget content. Genre focus. FAST model.',
    baseMatchScore: 72,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Roku Channel',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Comedy', 'Thriller', 'Documentary'],
    contentStrategy: 'Free streaming with original content. Quibi library acquired.',
    recentAcquisitions: ['Weird: The Al Yankovic Story', 'Die Hart', 'Reno 911!'],
    budgetRange: '\$2M - \$15M',
    submissionTip: 'Accessible content for broad audience.',
    baseMatchScore: 71,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Pluto TV',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Comedy', 'Action', 'Documentary'],
    contentStrategy: 'Free streaming. Paramount-owned. FAST pioneer.',
    recentAcquisitions: ['South Park', 'Star Trek', 'Paramount library'],
    budgetRange: '\$1M - \$10M',
    submissionTip: 'Library content and low-budget originals.',
    baseMatchScore: 70,
    acceptsUnsolicited: false,
    territoryFocus: 'US/International',
  ),
  BuyerProfile(
    name: 'BET+',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Comedy', 'Romance', 'Thriller'],
    contentStrategy: 'Black-focused streaming. Tyler Perry partnership.',
    recentAcquisitions: ['Tyler Perry content', 'Sistas', 'The Oval'],
    budgetRange: '\$3M - \$20M',
    submissionTip: 'Black stories and talent essential. Family drama expertise.',
    baseMatchScore: 76,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Shudder',
    type: 'Streamer',
    preferredGenres: ['Horror', 'Thriller', 'Sci-Fi'],
    contentStrategy: 'Horror-focused streaming. AMC-owned. Genre expertise.',
    recentAcquisitions: ['Creepshow', 'V/H/S franchise', 'Host', 'Skinamarink'],
    budgetRange: '\$500K - \$5M',
    submissionTip: 'Horror essential. Low budget model. Cult appeal.',
    baseMatchScore: 81,
    acceptsUnsolicited: true,
    territoryFocus: 'US/International',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL PRODUCTION COMPANIES
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'Working Title Films',
    type: 'Production Company',
    preferredGenres: ['Comedy', 'Romance', 'Drama', 'Action'],
    contentStrategy: 'Universal partnership. British talent focus. Four Weddings model.',
    recentAcquisitions: ['Darkest Hour', 'Les Misérables', 'Baby Driver', 'The Theory of Everything'],
    budgetRange: '\$15M - \$80M',
    submissionTip: 'British sensibility with global appeal. Star-driven vehicles.',
    baseMatchScore: 85,
    acceptsUnsolicited: false,
    territoryFocus: 'UK/Global',
  ),
  BuyerProfile(
    name: 'Annapurna Pictures',
    type: 'Production Company',
    preferredGenres: ['Drama', 'Comedy', 'Thriller', 'Sci-Fi'],
    contentStrategy: 'Megan Ellison\'s company. Prestige focus. Paul Thomas Anderson home.',
    recentAcquisitions: ['Her', 'American Hustle', 'Phantom Thread', 'If Beale Street Could Talk'],
    budgetRange: '\$15M - \$60M',
    submissionTip: 'Auteur-driven material. Awards potential essential.',
    baseMatchScore: 88,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Makeready',
    type: 'Production Company',
    preferredGenres: ['Drama', 'Thriller', 'Comedy', 'Horror'],
    contentStrategy: 'Brad Weston\'s company. Quality focus with commercial viability.',
    recentAcquisitions: ['The Art of Racing in the Rain', 'No Time to Die', 'Last Night in Soho'],
    budgetRange: '\$20M - \$80M',
    submissionTip: 'Commercial viability with quality storytelling.',
    baseMatchScore: 83,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Black Bear Pictures',
    type: 'Production Company',
    preferredGenres: ['Drama', 'Thriller', 'Horror', 'Comedy'],
    contentStrategy: 'Genre expertise with awards potential. I, Tonya model.',
    recentAcquisitions: ['I, Tonya', 'The Imitation Game', 'Molly\'s Game', 'Neon-distributed films'],
    budgetRange: '\$10M - \$40M',
    submissionTip: 'Genre with elevated execution. Festival potential.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Temple Hill Entertainment',
    type: 'Production Company',
    preferredGenres: ['Romance', 'Drama', 'Young Adult', 'Comedy'],
    contentStrategy: 'YA adaptation expertise. Twilight, Maze Runner producer.',
    recentAcquisitions: ['The Fault in Our Stars', 'Love, Simon', 'Five Feet Apart', 'After'],
    budgetRange: '\$15M - \$60M',
    submissionTip: 'YA book adaptations. Romance expertise.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Vertigo Entertainment',
    type: 'Production Company',
    preferredGenres: ['Horror', 'Thriller', 'Sci-Fi', 'Fantasy'],
    contentStrategy: 'Roy Lee\'s company. Asian horror remake expertise. It producer.',
    recentAcquisitions: ['It', 'The Ring', 'The Grudge', 'Barbarian', 'Evil Dead Rise'],
    budgetRange: '\$15M - \$80M',
    submissionTip: 'Horror with IP potential. Asian horror remake expertise.',
    baseMatchScore: 87,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Original Film',
    type: 'Production Company',
    preferredGenres: ['Action', 'Comedy', 'Horror', 'Family'],
    contentStrategy: 'Neal Moritz\'s company. Fast & Furious franchise producer.',
    recentAcquisitions: ['Fast & Furious franchise', 'Sonic', 'Goosebumps', '21 Jump Street'],
    budgetRange: '\$80M - \$250M',
    submissionTip: 'Franchise-building action/comedy. Family-friendly IP adaptations.',
    baseMatchScore: 84,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'STXfilms',
    type: 'Mini-Major',
    preferredGenres: ['Action', 'Comedy', 'Thriller', 'Drama'],
    contentStrategy: 'Mid-budget theatrical focus. Star-driven packages.',
    recentAcquisitions: ['Bad Moms', 'The Upside', 'Hustlers', 'Greenland'],
    budgetRange: '\$20M - \$80M',
    submissionTip: 'Star-driven packages essential. Commercial four-quadrant appeal.',
    baseMatchScore: 79,
    acceptsUnsolicited: false,
    territoryFocus: 'Global',
  ),
  BuyerProfile(
    name: 'Broken Road Productions',
    type: 'Production Company',
    preferredGenres: ['Drama', 'Thriller', 'Horror', 'Sci-Fi'],
    contentStrategy: 'Todd Black\'s company. Quality commercial films.',
    recentAcquisitions: ['The Equalizer', 'The Pursuit of Happyness', 'Fences'],
    budgetRange: '\$20M - \$80M',
    submissionTip: 'Commercial quality dramas. Star vehicle development.',
    baseMatchScore: 82,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Point Grey Pictures',
    type: 'Production Company',
    preferredGenres: ['Comedy', 'Horror', 'Drama'],
    contentStrategy: 'Seth Rogen & Evan Goldberg company. R-rated comedy expertise.',
    recentAcquisitions: ['Superbad', 'This Is the End', 'Neighbors', 'The Interview', 'Good Boys'],
    budgetRange: '\$20M - \$60M',
    submissionTip: 'R-rated comedy with irreverent voice. Fresh comedic perspectives.',
    baseMatchScore: 83,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),

  // ═══════════════════════════════════════════════════════════════════════════
  // TELEVISION FOCUSED
  // ═══════════════════════════════════════════════════════════════════════════
  
  BuyerProfile(
    name: 'FX Productions',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Comedy', 'Horror', 'Thriller'],
    contentStrategy: 'Premium cable quality. Prestige limited series. Hulu integration.',
    recentAcquisitions: ['Shōgun', 'The Bear', 'Welcome to Wrexham', 'Fargo'],
    budgetRange: '\$8M - \$20M per episode',
    submissionTip: 'Prestige limited series. Bold creative vision.',
    baseMatchScore: 88,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'AMC Studios',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Horror', 'Thriller', 'Sci-Fi'],
    contentStrategy: 'Walking Dead universe. Interview with the Vampire. AMC+ streaming.',
    recentAcquisitions: ['The Walking Dead', 'Interview with the Vampire', 'Dark Winds'],
    budgetRange: '\$5M - \$15M per episode',
    submissionTip: 'Genre drama expertise. Horror and thriller focus.',
    baseMatchScore: 81,
    acceptsUnsolicited: false,
    territoryFocus: 'US/Global',
  ),
  BuyerProfile(
    name: 'Showtime',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Thriller', 'Comedy', 'Documentary'],
    contentStrategy: 'Premium cable. Paramount+ integration. Dexter, Yellowjackets model.',
    recentAcquisitions: ['Yellowjackets', 'Dexter: New Blood', 'The Chi', 'Super Pumped'],
    budgetRange: '\$5M - \$15M per episode',
    submissionTip: 'Edgy premium content. Limited series preferred.',
    baseMatchScore: 80,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
  BuyerProfile(
    name: 'Starz',
    type: 'Streamer',
    preferredGenres: ['Drama', 'Action', 'Romance', 'Thriller'],
    contentStrategy: 'Diverse-led content. Power universe. Lionsgate-owned.',
    recentAcquisitions: ['Power Book II: Ghost', 'BMF', 'Outlander', 'P-Valley'],
    budgetRange: '\$4M - \$12M per episode',
    submissionTip: 'Diverse voices and creators. Franchise potential valued.',
    baseMatchScore: 78,
    acceptsUnsolicited: false,
    territoryFocus: 'US',
  ),
];

/// Getter for easy access
List<BuyerProfile> get allBuyers => expandedBuyerDatabase;

/// Get buyers by type
List<BuyerProfile> getBuyersByType(String type) {
  return expandedBuyerDatabase.where((b) => b.type == type).toList();
}

/// Get buyers by genre
List<BuyerProfile> getBuyersByGenre(String genre) {
  return expandedBuyerDatabase.where((b) => b.preferredGenres.contains(genre)).toList();
}

/// Get buyers that accept unsolicited submissions
List<BuyerProfile> get buyersAcceptingUnsolicited {
  return expandedBuyerDatabase.where((b) => b.acceptsUnsolicited).toList();
}
